#!/usr/bin/env bash

function bootstrap {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  bundle --path "$shome/vendor/bundle" --binstubs "$shome/vendor/bundle/bin"
  ln -nfs ../vendor/bundle/bin/tugboat bin/
}

bootstrap
