#!/usr/bin/env bash

function bootstrap {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  app compile bundler
  ln -nfs ../vendor/bundle/bin/tugboat bin/
}

bootstrap
